package br.unicesumar.entity;

public enum EscolaridadeResponsavel {
    ANALFABETO, ALFABETIZACAO_ADULTOS, FUNDAMENTAL_INCOMPLETO, FUNDAMENTAL_COMPLETO, SUPLETIVO_FUNDAMENTAL_INCOMPLETO, 
    SUPLETIV_FUNDAMENTAL_COMPLETO, MEDIO_INCOMPLETO, MEDIO_COMPLETO, SUPLETIVO_MEDIO_INCOMPLETO, SUPLETIVO_MEDIO_COMPLETO,
    MEDIO_TECNICO_INCOMPLETO, MEDIO_TECNICO_COMPLETO, SUPERIOR_INCOMPLETO, SUPERIOR_COMPLETO, PRE_VESTIBULAR
}