package br.unicesumar.entity;

public enum Formacao {
	FUNDAMENTAL_INCOMPLETO, MEDIO_INCOMPLETO, MEDIO_TECNICO_COMPLETO,
	SUPLETIVO_FUNDAMENTAL_INCOMPLETO, SUPLETIVO_MEDIO_INCOMPLETO,
	SUPERIOR_COMPLETO
}